name: speech_to_text_windows
description: Stub implementation of speech_to_text_windows for Windows builds
version: 1.0.0

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text_platform_interface: ^2.0.0

flutter:
  plugin:
    implements: speech_to_text
    platforms:
      windows:
        dartPluginClass: SpeechToTextWindows
